import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./componenet/sidebar/sidebar";
import { Box, Grid } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Grid container spacing={2}>
          <Grid md={3} bgcolor={"#3F1795"} paddingLeft={5} paddingTop={3} paddingRight={5}><Sidebar/></Grid>
          <Grid md={9} bgcolor={"#F3EFFF"} paddingTop={5} paddingLeft={5} paddingRight={5} >  {children}</Grid>
        </Grid>
      
      
        
        
       
        
        </body>
    </html>
  );
}
